#!/bin/bash
#
# Show today's or yesterdays log file generated by wlgw-check.sh

# Uncomment this statement for debug echos
# DEBUG=1

TMPDIR="$HOME/tmp"
LOGFILE="gateway.log"

# Get today's date
date_now=$(date "+%Y %m %d")
datespec=$date_now

# Find total lines in log file
total_lines=$(wc -l $TMPDIR/$LOGFILE | cut -d' ' -f1)

if [ $# -gt 0 ] ; then
    # If there are any arguments then show yesterdays log

    # Get yesterdays date
    date_yest=$(date --date="yesterday" "+%Y %m %d")
    datespec=$date_yest
    # Get line number of required dates first entry
    start_line_numb=$(grep -n "$date_yest" $TMPDIR/$LOGFILE | head -n 1 | cut -d':' -f1)
    start_line_numb=$((start_line_numb-1))
    # Get line number of todays date first entry
    end_line_numb=$(grep -n "$date_now" $TMPDIR/$LOGFILE | head -n 1 | cut -d':' -f1)

    # number of lines starting at yesterdays first log entry
    numb_lines=$((total_lines - start_line_numb))
    # number of lines until start of todays date
    count_lines=$((end_line_numb - start_line_numb - 1))

    echo "Using date: $datespec, starting: $start_line_numb, ending: $end_line_numb, num lines: $count_lines"
    tail -n $numb_lines $TMPDIR/$LOGFILE | head -n $count_lines

else
    # Show todays log
    start_line_numb=$(grep -n "$datespec" $TMPDIR/$LOGFILE | head -n 1 | cut -d':' -f1)
    start_line_numb=$((start_line_numb-1))
    numb_lines=$((total_lines - start_line_numb))

    echo "Using date: $datespec, starting at line number: $start_line_numb, numb_lines: $numb_lines"
    tail -n $numb_lines $TMPDIR/$LOGFILE
fi
